### ISSUE TITLE
The problem about PCGrad

### ISSUE THREAD

**Issue by guozhiyao** [lucasmansilla/DGvGS#1]
The results of PCGrad reported in Table 1. seems to be similar to baseline. And the averge gradient cosine similarity shown in Fig 2. are all greater than 0, will this be the reason why PCGrad does not work?

**Comment by guozhiyao** [comment]
In addition, have you ever counted the proportion of setting zeros?

**Comment by lucasmansilla** [comment]
Hi @guozhiyao,

The reason why PCGrad does not work is something that we are still studying. Having domain gradients with non-negative cosine similarity could explain why PCGrad performs similarly to Deep-All.

In reference to the other question, we counted the agreement ratio to verify that there is more agreement between the gradients of training domains and a dummy domain than between training domains and a test domain.

**Comment by guozhiyao** [comment]
In my experiment, about 50% gradients will be set to 0, is that normal?

**Comment by lucasmansilla** [comment]
I do not know, it would be interesting to study it.
