### ISSUE TITLE
The link of PACS Dataset failed

### ISSUE THREAD

**Issue by GoodMan0** [lucasmansilla/DGvGS#2]
Hi! Thanks for sharing the work! But the link of PACS Dataset failed. Could you update the download link of PACS! Thank u

**Comment by GoodMan0** [comment]
By the way, could you please release your train and test splits for fair comparison?

**Comment by lucasmansilla** [comment]
Hi @GoodMan0,

The link to download the PACS dataset is now working. Here are the training and test splits that we used: [train_val_test_splits.zip](https://github.com/lucasmansilla/DGvGS/files/7841369/train_val_test_splits.zip)

Regards.

**Comment by GoodMan0** [comment]
Thanks
