### ISSUE TITLE
Does it support multi-gpu training?

### ISSUE THREAD

**Issue by BJTUJia** [lucasmansilla/DGvGS#3]
Hi there, thanks for this nice work! Your code looks very neat and clear. However, when I am trying gradient surgery on my own task, where 4 GPUs are utilized to load 4 source datasets, the error throws AttributeError: 'DataParallel' object has no attribute 'get_grads '. So I am wondering this may be caused by the multi-GPU training process. Can you kindly elaborate on this? How many GPUs do you use in your experiments?  Thanks!

**Comment by lucasmansilla** [comment]
Hi @BJTUJia,

I only used one GPU in my experiments, but I think what happens is that the model is wrapped by the DataParallel class and it is not possible to access its attributes, like get_grads. Anyway, I will do some research to try to add support for multiple GPUs soon.

**Comment by BJTUJia** [comment]
Thanks! I will look into this issue as well！
